--<ScriptOptions statementTerminator=";"/>

ALTER TABLE `PUBLIC`.`MARKETPLACE_LIBERECO_SHIPPING_METHOD` DROP CONSTRAINT `FK33A9BC4665C62BF2`;

ALTER TABLE `PUBLIC`.`MARKETPLACE_LIBERECO_PAYMENT_METHOD` DROP CONSTRAINT `FK7241134655219968`;

ALTER TABLE `PUBLIC`.`MARKETPLACE_LIBERECO_PAYMENT_METHOD` DROP CONSTRAINT `FK72411346A0CDDA0C`;

ALTER TABLE `PUBLIC`.`LIBERECO_LISTING_MARKETPLACE` DROP CONSTRAINT `FKB89A49308DAF3FAF`;

ALTER TABLE `PUBLIC`.`LIBERECO_LISTING_MARKETPLACE` DROP CONSTRAINT `FKB89A4930490DBCED`;

ALTER TABLE `PUBLIC`.`MARKETPLACE_LIBERECO_SHIPPING_METHOD` DROP CONSTRAINT `FK33A9BC46A0CDDA0C`;

ALTER TABLE `PUBLIC`.`LIBERECO_LISTING` DROP CONSTRAINT `FK4AEF36A465ED36EB`;

ALTER TABLE `PUBLIC`.`LIBERECO_LISTING` DROP CONSTRAINT `FK4AEF36A4DDB2981D`;

ALTER TABLE `PUBLIC`.`LIBERECO_PAYMENT_TEMPLATE` DROP CONSTRAINT `PRIMARY_KEY_70`;

ALTER TABLE `PUBLIC`.`LIBERECO_SHIPPING_TEMPLATE` DROP CONSTRAINT `CONSTRAINT_4`;

ALTER TABLE `PUBLIC`.`MARKETPLACE` DROP CONSTRAINT `PRIMARY_KEY_9`;

ALTER TABLE `PUBLIC`.`LIBERECO_PAYMENT_TEMPLATE` DROP CONSTRAINT `CONSTRAINT_70`;

ALTER TABLE `PUBLIC`.`LIBERECO_SHIPPING_METHOD` DROP CONSTRAINT `PRIMARY_KEY_21`;

ALTER TABLE `PUBLIC`.`LIBERECO_PAYMENT_METHOD` DROP CONSTRAINT `PRIMARY_KEY_D`;

ALTER TABLE `PUBLIC`.`MARKETPLACE` DROP CONSTRAINT `CONSTRAINT_9`;

ALTER TABLE `PUBLIC`.`LIBERECO_SHIPPING_TEMPLATE` DROP CONSTRAINT `PRIMARY_KEY_4`;

ALTER TABLE `PUBLIC`.`LIBERECO_PAYMENT_METHOD` DROP CONSTRAINT `CONSTRAINT_D`;

ALTER TABLE `PUBLIC`.`EBAY_LISTING` DROP CONSTRAINT `CONSTRAINT_C`;

ALTER TABLE `PUBLIC`.`LIBERECO_LISTING` DROP CONSTRAINT `PRIMARY_KEY_2`;

ALTER TABLE `PUBLIC`.`LIBERECO_LISTING` DROP CONSTRAINT `CONSTRAINT_2`;

ALTER TABLE `PUBLIC`.`LIBERECO_SHIPPING_METHOD` DROP CONSTRAINT `CONSTRAINT_21`;

DROP INDEX `PUBLIC`.`PRIMARY_KEY_D`;

DROP INDEX `PUBLIC`.`PRIMARY_KEY_9`;

DROP INDEX `PUBLIC`.`PRIMARY_KEY_21`;

DROP INDEX `PUBLIC`.`FK4AEF36A465ED36EB_INDEX_2`;

DROP INDEX `PUBLIC`.`PRIMARY_KEY_5`;

DROP INDEX `PUBLIC`.`PRIMARY_KEY_2`;

DROP INDEX `PUBLIC`.`FK4AEF36A4DDB2981D_INDEX_2`;

DROP INDEX `PUBLIC`.`PRIMARY_KEY_4`;

DROP INDEX `PUBLIC`.`CONSTRAINT_INDEX_9`;

DROP INDEX `PUBLIC`.`PRIMARY_KEY_70`;

DROP INDEX `PUBLIC`.`FK33A9BC46A0CDDA0C_INDEX_6`;

DROP INDEX `PUBLIC`.`CONSTRAINT_INDEX_6`;

DROP INDEX `PUBLIC`.`CONSTRAINT_INDEX_F`;

DROP INDEX `PUBLIC`.`FKB89A4930490DBCED_INDEX_2`;

DROP INDEX `PUBLIC`.`CONSTRAINT_INDEX_2`;

DROP INDEX `PUBLIC`.`FK72411346A0CDDA0C_INDEX_F`;

DROP TABLE `PUBLIC`.`MARKETPLACE_LIBERECO_SHIPPING_METHOD`;

DROP TABLE `PUBLIC`.`MARKETPLACE`;

DROP TABLE `PUBLIC`.`LIBERECO_LISTING_MARKETPLACE`;

DROP TABLE `PUBLIC`.`LIBERECO_SHIPPING_METHOD`;

DROP TABLE `PUBLIC`.`MARKETPLACE_LIBERECO_PAYMENT_METHOD`;

DROP TABLE `PUBLIC`.`LIBERECO_PAYMENT_TEMPLATE`;

DROP TABLE `PUBLIC`.`LIBERECO_PAYMENT_METHOD`;

DROP TABLE `PUBLIC`.`LIBERECO_SHIPPING_TEMPLATE`;

DROP TABLE `PUBLIC`.`EBAY_LISTING`;

DROP TABLE `PUBLIC`.`LIBERECO_LISTING`;

CREATE TABLE `PUBLIC`.`MARKETPLACE_LIBERECO_SHIPPING_METHOD` (
		`MARKETPLACE_ID` BIGINT NOT NULL,
		`SHIPPINGMETHODS_ID` BIGINT NOT NULL
	);

CREATE TABLE `PUBLIC`.`MARKETPLACE` (
		`ID` BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_B9BCF0F9_1C85_4836_A800_7F2C5D58139A) NOT NULL,
		`MARKETPLACENAME` VARCHAR(255) NOT NULL,
		`MARKETPLACESHORTNAME` VARCHAR(255)
	);

CREATE TABLE `PUBLIC`.`LIBERECO_LISTING_MARKETPLACE` (
		`LIBERECO_LISTING_ID` BIGINT NOT NULL,
		`MARKETPLACES_ID` BIGINT NOT NULL
	);

CREATE TABLE `PUBLIC`.`LIBERECO_SHIPPING_METHOD` (
		`ID` BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_2C928F32_FD58_4A6D_A3FF_F447FD453C31) NOT NULL,
		`NAME` VARCHAR(255),
		`SHIPPINGLEVELTYPE` VARCHAR(255)
	);

CREATE TABLE `PUBLIC`.`MARKETPLACE_LIBERECO_PAYMENT_METHOD` (
		`MARKETPLACE_ID` BIGINT NOT NULL,
		`PAYMENTMETHODS_ID` BIGINT NOT NULL
	);

CREATE TABLE `PUBLIC`.`LIBERECO_PAYMENT_TEMPLATE` (
		`ID` BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_F9B5DC80_4196_4917_B4CE_C04F77097913) NOT NULL,
		`CURRENCY` VARCHAR(255)
	);

CREATE TABLE `PUBLIC`.`LIBERECO_PAYMENT_METHOD` (
		`ID` BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_97B4BD96_8AC9_4061_932E_3C9D270D0D57) NOT NULL,
		`PAYMENTMETHODTYPE` VARCHAR(255)
	);

CREATE TABLE `PUBLIC`.`LIBERECO_SHIPPING_TEMPLATE` (
		`ID` BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_48E34A7C_B493_4319_87B1_FB78554C1F36) NOT NULL,
		`COUNTRY` VARCHAR(255),
		`POSTCODE` VARCHAR(255)
	);

CREATE TABLE `PUBLIC`.`EBAY_LISTING` (
		`DISPATCHTIMEMAX` INTEGER,
		`RETURNPOLICY` VARCHAR(255),
		`ID` BIGINT NOT NULL,
		`LISTINGSTATE` INTEGER
	);

CREATE TABLE `PUBLIC`.`LIBERECO_LISTING` (
		`ID` BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_0B55BA46_6E80_4DFD_A5CF_E74D47AC1827) NOT NULL,
		`CATEGORY` VARCHAR(255),
		`CONDITION` VARCHAR(255),
		`DESCRIPTION` VARCHAR(255),
		`LISTINGDURATION` TIMESTAMP,
		`LISTINGSTATE` VARCHAR(255),
		`NAME` VARCHAR(255),
		`PICTURE` VARBINARY(255),
		`PRICE` DOUBLE,
		`QUANTITY` INTEGER,
		`USERID` VARCHAR(255),
		`LISTINGPAYMENT_ID` BIGINT,
		`LISTINGSHIPPING_ID` BIGINT
	);

CREATE UNIQUE INDEX `PUBLIC`.`PRIMARY_KEY_D` ON `PUBLIC`.`LIBERECO_PAYMENT_METHOD` (`ID` ASC);

CREATE UNIQUE INDEX `PUBLIC`.`PRIMARY_KEY_9` ON `PUBLIC`.`MARKETPLACE` (`ID` ASC);

CREATE UNIQUE INDEX `PUBLIC`.`PRIMARY_KEY_21` ON `PUBLIC`.`LIBERECO_SHIPPING_METHOD` (`ID` ASC);

CREATE INDEX `PUBLIC`.`FK4AEF36A465ED36EB_INDEX_2` ON `PUBLIC`.`LIBERECO_LISTING` (`LISTINGPAYMENT_ID` ASC);

CREATE UNIQUE INDEX `PUBLIC`.`PRIMARY_KEY_5` ON `PUBLIC`.`EBAY_LISTING` (`ID` ASC);

CREATE UNIQUE INDEX `PUBLIC`.`PRIMARY_KEY_2` ON `PUBLIC`.`LIBERECO_LISTING` (`ID` ASC);

CREATE INDEX `PUBLIC`.`FK4AEF36A4DDB2981D_INDEX_2` ON `PUBLIC`.`LIBERECO_LISTING` (`LISTINGSHIPPING_ID` ASC);

CREATE UNIQUE INDEX `PUBLIC`.`PRIMARY_KEY_4` ON `PUBLIC`.`LIBERECO_SHIPPING_TEMPLATE` (`ID` ASC);

CREATE UNIQUE INDEX `PUBLIC`.`CONSTRAINT_INDEX_9` ON `PUBLIC`.`MARKETPLACE` (`MARKETPLACENAME` ASC);

CREATE UNIQUE INDEX `PUBLIC`.`PRIMARY_KEY_70` ON `PUBLIC`.`LIBERECO_PAYMENT_TEMPLATE` (`ID` ASC);

CREATE INDEX `PUBLIC`.`FK33A9BC46A0CDDA0C_INDEX_6` ON `PUBLIC`.`MARKETPLACE_LIBERECO_SHIPPING_METHOD` (`MARKETPLACE_ID` ASC);

CREATE UNIQUE INDEX `PUBLIC`.`CONSTRAINT_INDEX_6` ON `PUBLIC`.`MARKETPLACE_LIBERECO_SHIPPING_METHOD` (`SHIPPINGMETHODS_ID` ASC);

CREATE UNIQUE INDEX `PUBLIC`.`CONSTRAINT_INDEX_F` ON `PUBLIC`.`MARKETPLACE_LIBERECO_PAYMENT_METHOD` (`PAYMENTMETHODS_ID` ASC);

CREATE INDEX `PUBLIC`.`FKB89A4930490DBCED_INDEX_2` ON `PUBLIC`.`LIBERECO_LISTING_MARKETPLACE` (`LIBERECO_LISTING_ID` ASC);

CREATE UNIQUE INDEX `PUBLIC`.`CONSTRAINT_INDEX_2` ON `PUBLIC`.`LIBERECO_LISTING_MARKETPLACE` (`MARKETPLACES_ID` ASC);

CREATE INDEX `PUBLIC`.`FK72411346A0CDDA0C_INDEX_F` ON `PUBLIC`.`MARKETPLACE_LIBERECO_PAYMENT_METHOD` (`MARKETPLACE_ID` ASC);

ALTER TABLE `PUBLIC`.`LIBERECO_PAYMENT_TEMPLATE` ADD CONSTRAINT `PRIMARY_KEY_70` UNIQUE (`ID`);

ALTER TABLE `PUBLIC`.`LIBERECO_SHIPPING_TEMPLATE` ADD CONSTRAINT `CONSTRAINT_4` PRIMARY KEY (`ID`);

ALTER TABLE `PUBLIC`.`MARKETPLACE` ADD CONSTRAINT `PRIMARY_KEY_9` UNIQUE (`ID`);

ALTER TABLE `PUBLIC`.`LIBERECO_PAYMENT_TEMPLATE` ADD CONSTRAINT `CONSTRAINT_70` PRIMARY KEY (`ID`);

ALTER TABLE `PUBLIC`.`LIBERECO_SHIPPING_METHOD` ADD CONSTRAINT `PRIMARY_KEY_21` UNIQUE (`ID`);

ALTER TABLE `PUBLIC`.`LIBERECO_PAYMENT_METHOD` ADD CONSTRAINT `PRIMARY_KEY_D` UNIQUE (`ID`);

ALTER TABLE `PUBLIC`.`MARKETPLACE` ADD CONSTRAINT `CONSTRAINT_9` PRIMARY KEY (`ID`);

ALTER TABLE `PUBLIC`.`LIBERECO_SHIPPING_TEMPLATE` ADD CONSTRAINT `PRIMARY_KEY_4` UNIQUE (`ID`);

ALTER TABLE `PUBLIC`.`LIBERECO_PAYMENT_METHOD` ADD CONSTRAINT `CONSTRAINT_D` PRIMARY KEY (`ID`);

ALTER TABLE `PUBLIC`.`EBAY_LISTING` ADD CONSTRAINT `CONSTRAINT_C` PRIMARY KEY (`ID`);

ALTER TABLE `PUBLIC`.`LIBERECO_LISTING` ADD CONSTRAINT `PRIMARY_KEY_2` UNIQUE (`ID`);

ALTER TABLE `PUBLIC`.`LIBERECO_LISTING` ADD CONSTRAINT `CONSTRAINT_2` PRIMARY KEY (`ID`);

ALTER TABLE `PUBLIC`.`LIBERECO_SHIPPING_METHOD` ADD CONSTRAINT `CONSTRAINT_21` PRIMARY KEY (`ID`);

ALTER TABLE `PUBLIC`.`MARKETPLACE_LIBERECO_SHIPPING_METHOD` ADD CONSTRAINT `FK33A9BC4665C62BF2` FOREIGN KEY (`SHIPPINGMETHODS_ID`)
	REFERENCES `PUBLIC`.`LIBERECO_SHIPPING_METHOD` (`ID`)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE `PUBLIC`.`MARKETPLACE_LIBERECO_PAYMENT_METHOD` ADD CONSTRAINT `FK7241134655219968` FOREIGN KEY (`PAYMENTMETHODS_ID`)
	REFERENCES `PUBLIC`.`LIBERECO_PAYMENT_METHOD` (`ID`)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE `PUBLIC`.`MARKETPLACE_LIBERECO_PAYMENT_METHOD` ADD CONSTRAINT `FK72411346A0CDDA0C` FOREIGN KEY (`MARKETPLACE_ID`)
	REFERENCES `PUBLIC`.`MARKETPLACE` (`ID`)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE `PUBLIC`.`LIBERECO_LISTING_MARKETPLACE` ADD CONSTRAINT `FKB89A49308DAF3FAF` FOREIGN KEY (`MARKETPLACES_ID`)
	REFERENCES `PUBLIC`.`MARKETPLACE` (`ID`)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE `PUBLIC`.`LIBERECO_LISTING_MARKETPLACE` ADD CONSTRAINT `FKB89A4930490DBCED` FOREIGN KEY (`LIBERECO_LISTING_ID`)
	REFERENCES `PUBLIC`.`LIBERECO_LISTING` (`ID`)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE `PUBLIC`.`MARKETPLACE_LIBERECO_SHIPPING_METHOD` ADD CONSTRAINT `FK33A9BC46A0CDDA0C` FOREIGN KEY (`MARKETPLACE_ID`)
	REFERENCES `PUBLIC`.`MARKETPLACE` (`ID`)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE `PUBLIC`.`LIBERECO_LISTING` ADD CONSTRAINT `FK4AEF36A465ED36EB` FOREIGN KEY (`LISTINGPAYMENT_ID`)
	REFERENCES `PUBLIC`.`LIBERECO_PAYMENT_TEMPLATE` (`ID`)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE `PUBLIC`.`LIBERECO_LISTING` ADD CONSTRAINT `FK4AEF36A4DDB2981D` FOREIGN KEY (`LISTINGSHIPPING_ID`)
	REFERENCES `PUBLIC`.`LIBERECO_SHIPPING_TEMPLATE` (`ID`)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

